#!/usr/bin/env python3
"""Generate outline variants of the sport icons.

Each source icon is a solid coloured disc with white artwork painted on top.
The outline variant swaps the two: a white disc with the artwork in the disc's
colour.  Nothing is added or removed, so the drawing keeps exactly the same
bounding box as its source -- which matters when the icons are included in
LaTeX, where a changed ink extent changes the typeset size.

Path data, transforms and the document's coordinate system are never touched.

Usage:
    python3 make_outline.py                  # every icon next to this script
    python3 make_outline.py golf.svg wrestling.svg
    python3 make_outline.py --src sports --out sports/outline
"""

import argparse
import re
import sys
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

SVG = "http://www.w3.org/2000/svg"
INKSCAPE = "http://www.inkscape.org/namespaces/inkscape"
SODIPODI = "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"

NAMESPACES = {
    "": SVG,
    "dc": "http://purl.org/dc/elements/1.1/",
    "cc": "http://creativecommons.org/ns#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "sodipodi": SODIPODI,
    "inkscape": INKSCAPE,
    "xlink": "http://www.w3.org/1999/xlink",
}

PAINT_PROPS = ("fill", "stroke")
WHITE = {"#ffffff", "#fff", "white"}
UNPAINTED = {"none", "transparent"}
MARKER = " generated by make_outline.py from the matching icon in the parent directory "


class IconError(Exception):
    """A source icon does not match the expected disc + artwork structure."""


def get_paint(el, prop):
    """Effective paint for one property: inline style wins over the attribute."""
    style = el.get("style")
    if style:
        for decl in style.split(";"):
            name, sep, value = decl.partition(":")
            if sep and name.strip() == prop:
                return value.strip().lower()
    value = el.get(prop)
    return value.strip().lower() if value else None


def set_paint(el, prop, value):
    """Rewrite an existing paint declaration in place, wherever it is set."""
    style = el.get("style")
    if style and re.search(rf"(^|;)\s*{prop}\s*:", style):
        el.set("style", re.sub(
            rf"(^|;)(\s*){prop}\s*:[^;]*",
            lambda m: f"{m.group(1)}{m.group(2)}{prop}:{value}",
            style,
        ))
    if el.get(prop) is not None:
        el.set(prop, value)


def paint_counts(el):
    """Every concrete paint colour in this subtree, with how often it is set."""
    counts = Counter()
    for node in el.iter():
        for prop in PAINT_PROPS:
            value = get_paint(node, prop)
            if value and value not in UNPAINTED:
                counts[value] += 1
    return counts


def swap_paints(el, colour, warnings):
    """Exchange white and `colour` throughout this subtree."""
    mapping = {white: colour for white in WHITE}
    mapping[colour] = "#ffffff"
    changed = 0
    for node in el.iter():
        for prop in PAINT_PROPS:
            value = get_paint(node, prop)
            if value is None or value in UNPAINTED:
                continue
            if value in mapping:
                set_paint(node, prop, mapping[value])
                changed += 1
            else:
                warnings.add(value)
    return changed


def find_layer(root):
    """The group holding the drawing: the Inkscape layer, else the first <g>."""
    for child in root:
        if child.tag == f"{{{SVG}}}g" and child.get(f"{{{INKSCAPE}}}groupmode") == "layer":
            return child
    for child in root:
        if child.tag == f"{{{SVG}}}g":
            return child
    raise IconError("no <g> container found under <svg>")


def build_outline(tree):
    """Convert a parsed icon in place. Returns a short summary string."""
    root = tree.getroot()
    if any(node.tag == ET.Comment and node.text == MARKER for node in root.iter()):
        raise IconError("already an outline icon")

    layer = find_layer(root)
    groups = [child for child in layer if child.tag == f"{{{SVG}}}g"]
    if len(groups) < 2:
        raise IconError(f"expected a disc group plus artwork groups, found {len(groups)}")

    disc = groups[0]
    disc_colours = Counter({c: n for c, n in paint_counts(disc).items() if c not in WHITE})
    if not disc_colours:
        raise IconError(f"first group <{disc.get('id')}> is not a coloured disc")
    colour = disc_colours.most_common(1)[0][0]

    warnings = set()
    changed = swap_paints(layer, colour, warnings)

    root.insert(0, ET.Comment(MARKER))

    summary = (f"disc <{disc.get('id')}>: swapped {colour} <-> #ffffff "
               f"across {changed} declaration(s) in {len(groups)} group(s)")
    if warnings:
        summary += f"  [warning: left as-is: {', '.join(sorted(warnings))}]"
    return summary


def convert(src_path, out_path):
    parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
    tree = ET.parse(src_path, parser=parser)
    summary = build_outline(tree)

    root = tree.getroot()
    if root.get(f"{{{SODIPODI}}}docname"):
        root.set(f"{{{SODIPODI}}}docname", out_path.name)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(ET.tostring(root, encoding="unicode") + "\n", encoding="utf-8")
    return summary


def main(argv=None):
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("icons", nargs="*", help="specific .svg files (default: all in --src)")
    ap.add_argument("--src", type=Path, default=here, help="source directory (default: %(default)s)")
    ap.add_argument("--out", type=Path, default=None, help="output directory (default: <src>/outline)")
    args = ap.parse_args(argv)

    out_dir = args.out or args.src / "outline"
    if args.icons:
        sources = [Path(i) if Path(i).exists() else args.src / i for i in args.icons]
    else:
        sources = sorted(args.src.glob("*.svg"))

    if not sources:
        print(f"no .svg files found in {args.src}", file=sys.stderr)
        return 1

    for prefix, uri in NAMESPACES.items():
        ET.register_namespace(prefix, uri)

    failures = 0
    for src in sources:
        try:
            summary = convert(src, out_dir / src.name)
        except (IconError, ET.ParseError, OSError) as exc:
            print(f"skip {src.name}: {exc}", file=sys.stderr)
            failures += 1
        else:
            print(f"{src.name} -> {out_dir / src.name}: {summary}")

    return 1 if failures and failures == len(sources) else 0


if __name__ == "__main__":
    sys.exit(main())
